### ISSUE TITLE
试着写了个脚本测试copa吞吐量，但达不到瓶颈链路的带宽

### ISSUE THREAD

**Issue by mooleetzi** [SoonyangZhang/ns3-tcp-bbr#1]
链路配置是这样
`Config::SetDefault ("ns3::TcpSocket::SndBufSize", UintegerValue (4194304));
  Config::SetDefault ("ns3::TcpSocket::RcvBufSize", UintegerValue (6291456));
  Config::SetDefault ("ns3::TcpSocket::InitialCwnd", UintegerValue (10));
  Config::SetDefault ("ns3::TcpSocket::DelAckCount", UintegerValue (delAckCount));
  Config::SetDefault ("ns3::TcpSocket::SegmentSize", UintegerValue (1448));
  Config::SetDefault ("ns3::DropTailQueue<Packet>::MaxSize", QueueSizeValue (QueueSize ("1p")));
  Config::SetDefault (queueDisc + "::MaxSize", QueueSizeValue (QueueSize ("100p")));
  Config::SetDefault ("ns3::TcpSocketState::EnablePacing", BooleanValue (true));`

拓扑长这样
```
//           1000 Mbps           10Mbps          1000 Mbps
//  Sender -------------- R1 -------------- R2 -------------- Receiver
//              5ms               10ms               5ms
//
```
得到的仿真吞吐量是这样的

![throughput](https://user-images.githubusercontent.com/42628885/179753976-668c6d86-21c2-47f5-b534-b48d274499b0.png)

**Comment by mooleetzi** [comment]
测试的是copa2

**Comment by SoonyangZhang** [comment]
你可以参考这里 https://github.com/facebookincubator/mvfst/blob/main/quic/congestion_control/Copa2.cpp  对比一下。看看有啥问题。

**Comment by mooleetzi** [comment]
好的，谢谢
