### ISSUE TITLE
如何设置tcp发包的时间间隔？

### ISSUE THREAD

**Issue by Jadaeu** [SoonyangZhang/ns3-tcp-bbr#11]
作者您好！我想测试一下bbr在链路数据不是完全饱和状态下的瓶颈带宽的探测性能，因此尝试设置tcp的发包时间间隔来限制链路中的数据量，多次设置都没有成功，能否给点意见呢？

**Comment by SoonyangZhang** [comment]
在应用层调用socket，按照一定间隔发送数据包，比如泊松分布，或者使用 on off application (https://github.com/SoonyangZhang/ns3-tcp-bbr/blob/main/ns-3.33/src/applications/model/onoff-application.cc)。
这个不是传输层的事，也就是说，你需要写点代码。

**Comment by Jadaeu** [comment]
好的，谢谢！
