### ISSUE TITLE
安装bbr到新版本

### ISSUE THREAD

**Issue by xueduanyue** [SoonyangZhang/ns3-tcp-bbr#12]
作者您好，我希望把bbr迁移到3.35版本。
我替换了bbr，bbr-debug和tcp-rate-ops文件，修改了wscript

报错，似乎是迁移时少了某个操作：
In file included from src/internet/bindings/ns3module.cc:1:
src/internet/bindings/ns3module.h:9306:44: error: ‘ns3::TcpBbr::BbrMode_t’ has not been declared
 9306 |     inline void SetBbrState__parent_caller(ns3::TcpBbr::BbrMode_t state)
      |                                            ^~~
src/internet/bindings/ns3module.h: In member function ‘uint32_t PyNs3TcpBbr__PythonHelper::AckAggregationCwnd__parent_caller()’:
src/internet/bindings/ns3module.h:9207:27: error: ‘AckAggregationCwnd’ is not a member of ‘ns3::TcpBbr’
 9207 |     { return ns3::TcpBbr::AckAggregationCwnd(); }
      |                           ^~~~~~~~~~~~~~~~~~
src/internet/bindings/ns3module.h: In member function ‘void PyNs3TcpBbr__PythonHelper::CheckCyclePhase__parent_caller(ns3::Ptr<ns3::TcpSocketState>, const ns3::TcpRateOps::TcpRateSample&)’:
src/internet/bindings/ns3module.h:9215:20: error: ‘CheckCyclePhase’ is not a member of ‘ns3::TcpBbr’
 9215 |     { ns3::TcpBbr::CheckCyclePhase(tcb, rs); }
      |                    ^~~~~~~~~~~~~~~
src/internet/bindings/ns3module.h: In member function ‘void PyNs3TcpBbr__PythonHelper::CheckFullPipe__parent_caller(const ns3::TcpRateOps::TcpRateSample&)’:
src/internet/bindings/ns3module.h:9223:20: error: ‘CheckFullPipe’ is not a member of ‘ns3::TcpBbr’
 9223 |     { ns3::TcpBbr::CheckFullPipe(rs); }
      |                    ^~~~~~~~~~~~~
src/internet/bindings/ns3module.h: In member function ‘void PyNs3TcpBbr__PythonHelper::CheckProbeRTT__parent_caller(ns3::Ptr<ns3::TcpSocketState>, const ns3::TcpRateOps::TcpRateSample&)’:
src/internet/bindings/ns3module.h:9227:20: error: ‘CheckProbeRTT’ is not a member of ‘ns3::TcpBbr’
 9227 |     { ns3::TcpBbr::CheckProbeRTT(tcb, rs); }
      |                    ^~~~~~~~~~~~~
src/internet/bindings/ns3module.h: In member function ‘void PyNs3TcpBbr__PythonHelper::EnterDrain__parent_caller()’:
src/internet/bindings/ns3module.h:9231:20: error: ‘EnterDrain’ is not a member of ‘ns3::TcpBbr’
 9231 |     { ns3::TcpBbr::EnterDrain(); }

**Comment by SoonyangZhang** [comment]
3.35 官方中有bbr: https://github.com/nsnam/ns-3-dev-git/blob/ns-3.35/src/internet/model/tcp-bbr.h
如果你想在3.35移植我的代码，可以把我实现的TcpBbr换个类名，比如TcpBbr1。
其他代码更改，你对着博客看看：https://blog.csdn.net/u010643777/article/details/117621291

**Comment by SoonyangZhang** [comment]
你要是对3.35的bbr不放心，也可以使用quic bbr: https://github.com/SoonyangZhang/quic-on-ns3

**Comment by xueduanyue** [comment]
目前看像是python binding的一些东西。在您的3.33版本的src/internet/bindings/modulegen__gcc_ILP32.py 文件里没有任何跟bbr相关的代码，而在3.35的官方版本里有很多bbr内容

**Comment by xueduanyue** [comment]
> 3.35 官方中有bbr: https://github.com/nsnam/ns-3-dev-git/blob/ns-3.35/src/internet/model/tcp-bbr.h 如果你想在3.35移植我的代码，可以把我实现的TcpBbr换个类名，比如TcpBbr1。 其他代码更改，你对着博客看看：https://blog.csdn.net/u010643777/article/details/117621291

从我的ns3经验看，把您的bbr换个名字应该就可以规避这个问题

**Comment by SoonyangZhang** [comment]
另外，需要改一个函数：https://github.com/SoonyangZhang/ns3-tcp-bbr/issues/8#issuecomment-1822579715

**Comment by SoonyangZhang** [comment]
另外，需要改一个函数：https://github.com/SoonyangZhang/ns3-tcp-bbr/issues/8#issuecomment-1822569593
```
uint32_t TcpBbr::GetSsThresh (Ptr<const TcpSocketState> tcb, uint32_t bytesInFlight) {
    SaveCongestionWindow(tcb->m_cWnd);
    //return tcb->m_ssThresh;
    return bytesInFlight;
}
```

**Comment by xueduanyue** [comment]
好的，非常感谢！
