### ISSUE TITLE
修改buffer大小

### ISSUE THREAD

**Issue by baiyuchen1228** [SoonyangZhang/ns3-tcp-bbr#2]
我在使用tcp-dumbbell.cc
![image](https://user-images.githubusercontent.com/71372497/223704560-8693e2b9-f9f6-4d4e-8182-4d9ad8a123a0.png)
想問看看你對於bbr與cubic共存時cubic的RTT會高於平常的一倍左右有想法嗎？

然後因此我想知道bottleneck-link 的 buffer大小
是跟這個有關嗎？
#define DEFAULT_PACKET_SIZE 1500

謝謝

**Comment by SoonyangZhang** [comment]
BBR flows (n0---->n1),Cubic flows(n4--->n5),different path, different delay.

**Comment by baiyuchen1228** [comment]
抱歉我沒問清楚，cubic理論上會在塞滿buffer的情況下傳遞，所以看中間那張圖他最大就只到150左右，但在共存的時候卻遠超過了最大值，有可能在哪裡發生了delay嗎？

還有我想知道要怎改buffer大小

**Comment by SoonyangZhang** [comment]
under the same path, if you collect delay trace of two flows, namely, flow1 and flow2,  the delay curves are similar, no matter which congestion control algorithm.
路径上的时延变化反映的是链路中buffer的占用情况，只要在相同的路径上，数据流观测到的时延曲线是相似的。你给出的图三，你确认一下，两个数据流不在同一条路径上。

**Comment by baiyuchen1228** [comment]
```
n0               n1
|                  | 
| l0              | l2
|                  | 
n2---l1------n3
|                  | 
|  l3             | l4
|                  | 
n4              n5
```

 In fig 2, I use cubic on n0 and n4, and trace n0 to n1 and n4 to n5. So I think the max rtt is 150ms when buffer is full.
 In fig 3, I use bbr on n0 and use cubic on n4, and trace n0 to n1 and n4 to n5. n4 to n5's rtt can high to 300ms.
I have no idea. maybe is retransmit?

**Comment by SoonyangZhang** [comment]
email me your code， and the command you run tcp-dumbbell.cc, and I will try to find  the problem.  
865678017@qq.com
Fig3 的结果是奇怪的，经过同一个瓶颈链路(n2-n3)的数据流，时延曲线理论上只有高度差异，不应该有走势差异。

**Comment by SoonyangZhang** [comment]
static NodeContainer BuildDumbbellTopo(LinkProperty *topoinfo,int links,int bottleneck_i,
                                    uint32_t buffer_ms,TriggerRandomLoss *trigger=nullptr)
param buffer_ms  wil config buffer length.

**Comment by SoonyangZhang** [comment]
I add a variable uint64_t totalTxBytes0=20000*1500; //line 286. It will decide the tramited packets of the two tcp BBR flows. And the results:
![rtt](https://user-images.githubusercontent.com/13272526/224483868-770d0c9e-2679-414c-b941-7fb15bfa444c.png)
