### ISSUE TITLE
throughtput not as expected

### ISSUE THREAD

**Issue by baiyuchen1228** [SoonyangZhang/ns3-tcp-bbr#4]
in tcp-dumbbell.cc,I use this command
`./waf --run "scratch/tcp-dumbbell --it=3 --cc1=bbr --cc2=bbr --folder=bbr1-dumbbell "`
bottleneck_bw is 12000000, but goodput only have approximately 10000. 
![image](https://user-images.githubusercontent.com/71372497/229061161-072c67bb-eb9b-4766-b617-24037637b1e6.png)
I want to know what happen, thanks

**Comment by SoonyangZhang** [comment]
12000000， 12Mbps？

**Comment by baiyuchen1228** [comment]
Yes,12Mbps and get 10000bps only

**Comment by SoonyangZhang** [comment]
11446.4 kbps ≈12Mpps.  Is there any question?

**Comment by baiyuchen1228** [comment]
Oh, I realized that I got the units wrong.
