### ISSUE TITLE
Just out of curiousity, Why is the code structured like this?

### ISSUE THREAD

**Issue by wlwl1011** [SoonyangZhang/ns3-tcp-bbr#6]
Hello :)
I was wondering if there was a reason you made the code like this!
I've checked that your code is as below.
"  
LinkProperty topoinfo1[] = {
        [0] = {0, 2, 0, 10},
        [1] = {2, 3, 0, 10},
        [2] = {3, 1, 0, 10},
        [3] = {2, 4, 0, 10},
        [4] = {3, 5, 0, 10},
    };

"

and in function which name is BuildDumbbellTopo,
"
    uint16_t src = topoinfo[i].nodes[0];
        uint16_t dst = topoinfo[i].nodes[1];
        uint32_t bps = topoinfo[i].bandwidth;
        uint32_t owd = topoinfo[i].propagation_ms;
"

I also confirmed that the topology you configured in the simulation is as follows.

/** Network topology
 *       n0            n1
 *        |            |
 *        | l0         | l2
 *        |            |
 *        n2---l1------n3
 *        |            |
 *        |  l3        | l4
 *        |            |
 *        n4           n5
 */

According to your code, if you check the src and dst parts of the five nodes in topoinfo1, the index number 3 node is src = 2, dst = 4.
Then the flow of data is from node1 to node2, from node2 to node3, from node3 to node1, from node2 to node4, from node3 to node5.
Is the topology you intended?
The flow of data seems to be weird if we keep it this way.
Shouldn't src = 4, dst = 2?

Can the data flow from node 4 to node 2 regardless of how it is? Or did you write the wrong code, or did you leave it like this as part of it?!

https://github.com/SoonyangZhang/ns3-tcp-bbr/blob/9d3ee50de5b3d5e30c06eddf773dd3a7ffc8bbe9/ns-3.33/scratch/tcp-dumbbell.cc#L199C4-L205C7

**Comment by wlwl1011** [comment]
I think the data flow in the current code is like this!

![IMG_7717](https://github.com/SoonyangZhang/ns3-tcp-bbr/assets/62577565/a30be2b9-afb9-4220-9aea-6792ab2f2963)

**Comment by wlwl1011** [comment]
I left an issue because I thought the normal flow of data should go this way! I'm so sorry if I asked you a strange question with my lack of knowledge.

![IMG_7718](https://github.com/SoonyangZhang/ns3-tcp-bbr/assets/62577565/2a3eceeb-2f85-4b40-9914-e342d435e9a6)

**Comment by SoonyangZhang** [comment]
Is there anything wrong？the packet can not flow to its destination?of course,you can build you own topology if you think i build is weird.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 19:37 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [SoonyangZhang/ns3-tcp-bbr] Just out of curiousity, Why is the codestructured like this? (Issue #6)




 
Hello :)
 I was wondering if there was a reason you made the code like this!
 I've checked that your code is as below.
 "
 LinkProperty topoinfo1[] = {
 [0] = {0, 2, 0, 10},
 [1] = {2, 3, 0, 10},
 [2] = {3, 1, 0, 10},
 [3] = {2, 4, 0, 10},
 [4] = {3, 5, 0, 10},
 };
 
"
 
and in function which name is BuildDumbbellTopo,
 "
 uint16_t src = topoinfo[i].nodes[0];
 uint16_t dst = topoinfo[i].nodes[1];
 uint32_t bps = topoinfo[i].bandwidth;
 uint32_t owd = topoinfo[i].propagation_ms;
 "
 
I also confirmed that the topology you configured in the simulation is as follows.
 
/** Network topology
  
   n0            n1  
 
    |            |  
 
    | l0         | l2  
 
    |            |  
 
    n2---l1------n3  
 
    |            |  
 
    |  l3        | l4  
 
    |            |  
 
    n4           n5  
  
*/
 
According to your code, if you check the src and dst parts of the five nodes in topoinfo1, the index number 3 node is src = 2, dst = 4.
 Then the flow of data is from node1 to node2, from node2 to node3, from node3 to node1, from node2 to node4, from node3 to node5.
 Is the topology you intended?
 The flow of data seems to be weird if we keep it this way.
 Shouldn't src = 4, dst = 2?
 
Can the data flow from node 4 to node 2 regardless of how it is? Or did you write the wrong code, or did you leave it like this as part of it?!
 
https://github.com/SoonyangZhang/ns3-tcp-bbr/blob/9d3ee50de5b3d5e30c06eddf773dd3a7ffc8bbe9/ns-3.33/scratch/tcp-dumbbell.cc#L199C4-L205C7

**Comment by wlwl1011** [comment]
Oh! I didn't leave an issue for another reason, but I left it because I was really curious...!🥹🥹

I am not good at English, so I would like to apologize if the tone you feel in my writing seems aggressive. (I think it's because I'm simply translating through a translator......)

**Comment by wlwl1011** [comment]
With the code written by Soonyang Zhang, which of the pictures I attached above is correct???
Pink, or yellow?

**Comment by SoonyangZhang** [comment]
This pic is right. n0 can n1 can send data to each other(bidirectional).so do n4 to n5.



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 27, 2023 19:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [SoonyangZhang/ns3-tcp-bbr] Just out of curiousity, Why is thecode structured like this? (Issue #6)




 
I left an issue because I thought the normal flow of data should go this way! I'm so sorry if I asked you a strange question with my lack of knowledge.

**Comment by wlwl1011** [comment]
Thanks a lot !!!!!!!!!!! 🧧🧧🧧🧧🧧🧧🧧🧧🧧🧧🧧😇
Have a great day!
