### ISSUE TITLE
bbr算法的cwnd 有明显异常

### ISSUE THREAD

**Issue by wangling952013** [SoonyangZhang/ns3-tcp-bbr#8]
2.43761	3067833
2.43761	3067832

bbr算法的cwnd 有明显异常的值，为什么

**Comment by SoonyangZhang** [comment]
把测试链路参数，数据流个数，描述清楚。不然，回答不了。我也看不出你给的两个值有啥异常。

**Comment by wangling952013** [comment]
代码：
/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2021 Northeastern University, China
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Authors: SongyangZhang <sonyang.chang@foxmail.com>
 * URL: https://github.com/SoonyangZhang/ns3-tcp-bbr
*/
#include <string>
#include <unistd.h>
#include<stdio.h>
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/applications-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/traffic-control-module.h"
#include "ns3/tcp-client-module.h"
using namespace ns3;
using namespace std;

NS_LOG_COMPONENT_DEFINE ("TcpTest");
static const double startTime=0;
static const double simDuration= 50.0;
#define DEFAULT_PACKET_SIZE 1500
static NodeContainer BuildExampleTopo (uint32_t bps,
                                       uint32_t msDelay,
                                       uint32_t msQdelay,
                                       bool enable_random_loss=false)
{
    NodeContainer nodes;
    nodes.Create (2);

    PointToPointHelper pointToPoint;
    pointToPoint.SetDeviceAttribute ("DataRate", DataRateValue  (DataRate (bps)));
    pointToPoint.SetChannelAttribute ("Delay", TimeValue (MilliSeconds (msDelay)));
    auto bufSize = std::max<uint32_t> (DEFAULT_PACKET_SIZE, bps * msQdelay / 8000);
    int packets=bufSize/DEFAULT_PACKET_SIZE;
    NS_LOG_INFO("buffer packet "<<packets);
    pointToPoint.SetQueue ("ns3::DropTailQueue",
                           "MaxSize", StringValue (std::to_string(1)+"p"));
    NetDeviceContainer devices = pointToPoint.Install (nodes);

    InternetStackHelper stack;
    stack.Install (nodes);

    TrafficControlHelper pfifoHelper;
    uint16_t handle = pfifoHelper.SetRootQueueDisc ("ns3::FifoQueueDisc", "MaxSize", StringValue (std::to_string(packets)+"p"));
    pfifoHelper.AddInternalQueues (handle, 1, "ns3::DropTailQueue", "MaxSize",StringValue (std::to_string(packets)+"p"));
    pfifoHelper.Install(devices);
    Ipv4AddressHelper address;
    std::string nodeip="10.1.1.0";
    address.SetBase (nodeip.c_str(), "255.255.255.0");
    address.Assign (devices);
    if(enable_random_loss){
        std::string errorModelType = "ns3::RateErrorModel";
        ObjectFactory factory;
        factory.SetTypeId (errorModelType);
        Ptr<ErrorModel> em = factory.Create<ErrorModel> ();
        devices.Get (1)->SetAttribute ("ReceiveErrorModel", PointerValue (em));
    }
    return nodes;
}
// ./waf --run "scratch/tcp-test --cc=bbr --folder=bbr"
int main(int argc, char *argv[])
{
    LogComponentEnable("TcpTest", LOG_LEVEL_ALL);
    LogComponentEnable("TcpClient", LOG_LEVEL_ALL);
    LogComponentEnable("TcpBbr", LOG_LEVEL_ALL);
    std::string cc("bbr");
    std::string folder_name("default");
    std::string pk_cc("cubic");

    CommandLine cmd;
    cmd.AddValue ("cc", "congestion algorithm",cc);
    cmd.AddValue ("folder", "folder name to collect data", folder_name);
    cmd.AddValue ("pk_cc", "PK congestion algorithm",pk_cc);
    cmd.Parse (argc, argv);
    uint32_t kMaxmiumSegmentSize=1400;
    Config::SetDefault("ns3::TcpSocket::SndBufSize", UintegerValue(200*kMaxmiumSegmentSize));
    Config::SetDefault("ns3::TcpSocket::RcvBufSize", UintegerValue(200*kMaxmiumSegmentSize));
    Config::SetDefault("ns3::TcpSocket::SegmentSize",UintegerValue(kMaxmiumSegmentSize));
    if(0==cc.compare("reno")||0==cc.compare("bic")||0==cc.compare("cubic")||
      0==cc.compare("bbr")||0==cc.compare("copa")){}
    else{
        NS_ASSERT_MSG(0,"please input correct cc");
    }
    if(0==pk_cc.compare("reno")||0==pk_cc.compare("bic")||0==pk_cc.compare("cubic")||
      0==pk_cc.compare("bbr")||0==pk_cc.compare("copa")){}
    else{
        NS_ASSERT_MSG(0,"please input correct pk_cc");
    }

    std::string trace_folder;
    
    {
        char buf[FILENAME_MAX];
        std::string trace_path=std::string (getcwd(buf, FILENAME_MAX))+"/traces/";
        trace_folder=trace_path+folder_name+"/";
        MakePath(trace_folder);
        TcpBbrDebug::SetTraceFolder(trace_folder.c_str());
        TcpTracer::SetTraceFolder(trace_folder.c_str());
    }
    uint32_t link_bw=6000000;
    uint32_t link_owd=50;
    uint32_t q_delay=200;
    NodeContainer topo;
    topo=BuildExampleTopo(link_bw,link_owd,q_delay);
    Ptr<Node> h1=topo.Get(0);
    Ptr<Node> h2=topo.Get(1);

    //for utility
    TcpTracer::SetExperimentInfo(3,link_bw);
    //for loss rate
    TcpTracer::SetLossRateFlag(true);

    uint16_t serv_port = 5000;
    //install server on h2
    Address tcp_sink_addr;
    {
        Ptr<Ipv4> ipv4 = h2->GetObject<Ipv4> ();
        Ipv4Address serv_ip= ipv4->GetAddress (1, 0).GetLocal();
        InetSocketAddress socket_addr=InetSocketAddress{serv_ip,serv_port};
        tcp_sink_addr=socket_addr;
        Ptr<TcpServer> server=CreateObject<TcpServer>(tcp_sink_addr);
        h2->AddApplication(server);
        server->SetStartTime (Seconds (0.0));
    }

    uint64_t totalTxBytes = 40000*1500;
    {
        Ptr<TcpClient>  client= CreateObject<TcpClient> (totalTxBytes,TcpClient::E_TRACE_ALL);
        h1->AddApplication(client);
        client->ConfigurePeer(tcp_sink_addr);
        client->SetCongestionAlgo(cc);
        client->SetStartTime (Seconds (startTime));
        client->SetStopTime (Seconds (simDuration));
    }
    {
        Ptr<TcpClient>  client= CreateObject<TcpClient> (totalTxBytes,TcpClient::E_TRACE_ALL);
        h1->AddApplication(client);
        client->ConfigurePeer(tcp_sink_addr);
        client->SetCongestionAlgo(pk_cc);
        client->SetStartTime (Seconds (startTime));
        client->SetStopTime (Seconds (simDuration));
    }
//    {
//        Ptr<TcpClient>  client= CreateObject<TcpClient> (totalTxBytes,TcpClient::E_TRACE_RTT|TcpClient::E_TRACE_INFLIGHT|TcpClient::E_TRACE_RATE);
//        h1->AddApplication(client);
//        client->ConfigurePeer(tcp_sink_addr);
//        client->SetCongestionAlgo(cc);
//        client->SetStartTime (Seconds (startTime+50));
//        client->SetStopTime (Seconds (simDuration));
//    }
    
    Simulator::Stop (Seconds (simDuration+10.0));
    Simulator::Run ();
    Simulator::Destroy ();
    return 0;
    
}
执行命令：./waf --run "scratch/tcp-bbr-pk-cubic --cc=bbr --folder=bbr-pk-cubic --pk_cc=cubic"
生成trace中，10.1.1.1_49153_10.1.1.2_5000_cwnd.txt 显示：
0.894885        74
0.908466        73
0.941434        72
1.19927 73
1.20121 74
1.22639 3067833
1.22639 3067832
1.45515 4
1.4978  6
1.50169 8
1.50363 9
1.50556 166
1.53273 165
1.5366  164
1.54242 163
1.5463  162

其中3067833和3067832明显太大，而且都是固定的

**Comment by wangling952013** [comment]
执行你给的测试程序：./waf --run "scratch/tcp-test --cc=bbr --folder=bbr"
在cwnd.txt里面也有发现，异常窗口值
：
51.7317 70
51.7356 71
51.7395 72
51.7453 73
51.7491 74
51.753  75
51.7724 76
51.7763 77
51.7879 3067833
51.7879 3067832
51.8907 109
51.8965 108
51.9295 107
51.9411 105
51.9624 104
51.9682 102
51.9721 100

**Comment by SoonyangZhang** [comment]
有日志信息，你可以试着调试一下。或者等我诊断。

**Comment by wangling952013** [comment]
> 有日志信息，你可以尝试调试一下。或者等我诊断。

我使用ns-3.4版本的bbr，没看到这个现象，是不是bbr移植问题？

**Comment by SoonyangZhang** [comment]
try this:
```c++
uint32_t TcpBbr::GetSsThresh (Ptr<const TcpSocketState> tcb, uint32_t bytesInFlight) {
    SaveCongestionWindow(tcb->m_cWnd);
    //return tcb->m_ssThresh;
    return bytesInFlight;
}
```

**Comment by SoonyangZhang** [comment]
```
void
TcpSocketBase::ProcessAck(const SequenceNumber32 &ackNumber, bool scoreboardUpdated,
                          uint32_t currentDelivered, const SequenceNumber32 &oldHeadSequence) {
  if (exitedFastRecovery)
    {
      NewAck (ackNumber, true);
      m_tcb->m_cWnd = m_tcb->m_ssThresh.Get ();
      m_recoveryOps->ExitRecovery (m_tcb);
      NS_LOG_DEBUG ("Leaving Fast Recovery; BytesInFlight() = " <<
                    BytesInFlight () << "; cWnd = " << m_tcb->m_cWnd);
    }
}
```
when tcp exits FastRecovery, m_tcb->m_cWnd = m_tcb->m_ssThresh.Get (), but in BBR, m_ssThresh is not used and is initialized as UINT32_MAX.

**Comment by wangling952013** [comment]
85.961  40
86.0773 38
86.182  40
86.182  4
86.1956 6
86.1956 4
86.2072 6
86.2072 4
86.2169 6
86.2169 4
86.2285 6
86.2285 4
86.2401 6
86.2401 4
86.2498 6
86.2498 4
86.2615 6
86.2615 4
86.277  6
86.277  4
86.2886 6

窗口中不间断出现4和6这连个值，也是因为bbr的问题？

**Comment by SoonyangZhang** [comment]
ProbeRTT, cwnd = 4. 
See the log 1_TcpBbr_info.txt.
Jon Snow, you know nothing about BBR.
For comparison with Cubic, use inflight instead. Since in ProbeBW, cwnd = 2 * BDP in BBR.

**Comment by wangling952013** [comment]
谢谢您的回答，您说得非常对！
但是我在tcp-bbr.cc中添加了窗口打印：
    m_debug->GetStram()<<ModeToString(m_mode)<<" "<<now.GetSeconds()<<" "
    <<instant_bw.GetBitRate()<<" "<<long_bw.GetBitRate()<<" "
    <<rtt_ms<<" "<<rs.m_bytesLoss<<" "<<tcb->m_cWnd/tcb->m_segmentSize<<std::endl;
然后我在1_TcpBbr_info.txt确实存在窗口为4的情况，没有窗口为6的情况
robe_rtt 181.78 1256023 1333192 396 0 4
probe_rtt 181.784 1270976 1333192 382 0 4
probe_rtt 181.788 1256023 1333192 370 0 4
probe_rtt 181.792 1304332 1333192 358 0 4
probe_rtt 181.796 1296704 1333192 345 0 4
probe_rtt 181.799 1312050 1333192 333 0 4
probe_rtt 181.803 1327763 1333192 321 0 4
probe_rtt 181.807 1377245 1377245 308 0 4
probe_rtt 181.811 1386067 1386067 293 0 4
probe_rtt 181.815 1382636 1386067 279 0 4
probe_rtt 181.819 1382636 1386067 266 0 4
probe_rtt 181.823 1382636 1386067 254 0 4
probe_bw 182.029 86661 1386067 211 0 56
probe_bw 182.045 173323 1386067 210 0 56
但是在cwnd.txt文件中却是有窗口为6的情况：
8.78286 58
8.9903  56
10.4055 58
10.4055 4
10.423  6
10.423  4
10.4404 6
10.4404 4
10.454  6
10.454  4
10.4695 6
10.4695 4
10.4869 6
10.4869 4

**Comment by SoonyangZhang** [comment]
Read the source code yourself and analysis why.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月23日(周四) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SoonyangZhang/ns3-tcp-bbr] bbr算法的cwnd 有明显异常 (Issue #8)




 
谢谢您的回答，您说得非常对！
 但是我在tcp-bbr.cc中添加了窗口打印：
 m_debug-&gt;GetStram()<<ModeToString(m_mode)<<" "<<now.GetSeconds()<<" "
 <<instant_bw.GetBitRate()<<" "<<long_bw.GetBitRate()<<" "
 <<rtt_ms<<" "<<rs.m_bytesLoss<<" "<m_cWnd/tcb-&gt;m_segmentSize<<std::endl;
 然后我在1_TcpBbr_info.txt确实存在窗口为4的情况，没有窗口为6的情况
 robe_rtt 181.78 1256023 1333192 396 0 4
 probe_rtt 181.784 1270976 1333192 382 0 4
 probe_rtt 181.788 1256023 1333192 370 0 4
 probe_rtt 181.792 1304332 1333192 358 0 4
 probe_rtt 181.796 1296704 1333192 345 0 4
 probe_rtt 181.799 1312050 1333192 333 0 4
 probe_rtt 181.803 1327763 1333192 321 0 4
 probe_rtt 181.807 1377245 1377245 308 0 4
 probe_rtt 181.811 1386067 1386067 293 0 4
 probe_rtt 181.815 1382636 1386067 279 0 4
 probe_rtt 181.819 1382636 1386067 266 0 4
 probe_rtt 181.823 1382636 1386067 254 0 4
 probe_bw 182.029 86661 1386067 211 0 56
 probe_bw 182.045 173323 1386067 210 0 56
 但是在cwnd.txt文件中却是有窗口为6的情况：
 8.78286 58
 8.9903  56
 10.4055 58
 10.4055 4
 10.423  6
 10.423  4
 10.4404 6
 10.4404 4
 10.454  6
 10.454  4
 10.4695 6
 10.4695 4
 10.4869 6
 10.4869 4
