### ISSUE TITLE
数据表示的含义

### ISSUE THREAD

**Issue by Jadaeu** [SoonyangZhang/ns3-tcp-bbr#9]
![image](https://github.com/SoonyangZhang/ns3-tcp-bbr/assets/105416501/d2b24df5-10a7-4254-96f2-754bdbb394a5)
作者您好，上面是得到的0_TcpBbr_info.txt文件中的一部分数据，第一列和第三列数据分别是时间和探测到的最大带宽吧？还想请问一下图中标红的三列数据分别表示什么含义呢？

**Comment by SoonyangZhang** [comment]
https://github.com/SoonyangZhang/ns3-tcp-bbr/blob/main/ns-3.33/src/internet/model/tcp-bbr.cc#L891
